# Dependencies
markdown:         kramdown
highlighter:      rouge



# Setup
title:            Statistical Consulting Program
tagline:          Stats
description:      "Department of Statistics, University of Chicago"
baseurl:          ""
newbaseurl:        /
url:              https://github.com/uofcstatdeptconsult.github.io
                  # the optional subpath of your site, e.g. "/my-jekyll-site/"
                  # This will apply to all pages in your Jekyll site.


root: /octo-5
paginate:         5
# paginate_path:    '/page:num'
                    # Or '/my-jekyll-site/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  
# List of links in the navigation bar
# List of links in the navigation bar
navbar-links:
  About the Statistics Consulting Workshop:
    - About the Workshop: "about"
    - Join us: "join"
    - Contact: "contact"
  Consulting Resources: "consult"
  Statistical Resources: "stat"

 

collections:
  pages:
    output: true
    permalink: /:path/
    
permalink: pretty

include: ['_pages', '_pages/foo']

# Custom vars
version:            2.0.1
# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME
